Part 19
lunulu/thinknetica-part19 pull request #1
Opened 2022-10-31 16:51 UTC by lunulu

2022-11-01 07:03 UTC, VidgarVii requested changes

2022-11-01 07:03 UTC, VidgarVii commented on rack/app.rb
> +      'content-type' => 'text/plain'
Для настройки ContentType по умолчанию можно воспользоваться настройкой через Rack::ContentType

https://www.rubydoc.info/gems/rack/Rack/ContentType

и этот код будет не нужным

2022-11-01 07:03 UTC, VidgarVii commented on rack/app.rb
> +  def call(env)
будет правильно оставить разделить классы на 2 группы:
1. группа - отвечают за обработку данных - проверка валидности данных, форматирование ответа (в них вообще не нужно никаких методов `call`, использовать их надо как сервисы), назовем их "форматтеры"
отправляешь данные в такой класс, а в приложении только формируешь ответ после обработки
в таком стиле:
```ruby
def response_body
  ...
  formatter = FormatTime.new(...)
  if formatter.valid?
    formatter.time
  else
    formatter.invalid_formats
  end
end
```

2022-11-03 16:52 UTC, BubuntuClu commented on rack/app.rb
> +    @formatter = FormatTime.new(format: req.params['format'])
почему formatter это инстанс переменная?

2022-11-03 18:13 UTC, lunulu commented on rack/app.rb
> +    @formatter = FormatTime.new(format: req.params['format'])
Забыл исправить

2022-11-03 18:13 UTC, merged